spring.application.name=dispatcher

# PostgreSQL connection string to the local dispatcher_db container
spring.datasource.url=jdbc:postgresql://db:5432/dispatcher_v1
spring.datasource.username=dispatcher_admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config (Validate schema against our pre-seeded SQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
